{
    'name': 'HMS',
    'description': "Dental clinic Managment",
    'depends': ['base', 'web'],
    'data': [
        'views/countries_views.xml',
        'views/patients_views.xml',
        'views/cities_views.xml',
        'views/appointment_view.xml',
        'views/contact_view.xml',
        'views/medical_histiry_views.xml',
        'views/quotations_views.xml',
        'views/treatments_views.xml',
        'views/quotation_treatment_viwes.xml',
        'views/teeth_views.xml',
        'views/treatment_plan_views.xml',
        'views/trealment_plan_lines_views.xml',
        'views/patient_attachments_views.xml',
        'views/payment_patient_views.xml',
        'views/patient_search_action.xml',
        'data/sequence.xml',
        'report/prescription_report.xml',
        'report/prescription_template.xml',
        'views/prescription_views.xml',
        'views/medicine_views.xml',
        'views/not_interested_reason_views.xml',
        'views/interest_list_views.xml',
        'views/lost_reason_views.xml',
        "wizards/appointment_cancel_wizard_views.xml",
        "wizards/contact_stage_wizard_view.xml",
        "wizards/not_interested_wizard_view.xml",
        "wizards/qualified_stage_view.xml",
        "wizards/details_recieved_wizard_view.xml",
        "wizards/quotation_prepare_wizard_view.xml",
        "wizards/lost_stage_wizard_view.xml",
        "report/report_prescription_action.xml",
        "report/report_prescription_template.xml",
    ],
    'assets': {
        'web.assets_backend': [
            'patients_list/static/src/js/patient_search.js',
            'patients_list/static/src/xml/patient_search_templates.xml',
            'patients_list/static/src/scss/patient_search.scss',
            'patients_list/static/src/js/today_appointments.js',
            'patients_list/static/src/xml/today_appointments.xml',
            'patients_list/static/src/scss/today_appointments.scss',
        ],
    },
    'license': 'LGPL-3',
}
